# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9a1d88856228b6b62f5cde52488f27313018d9aacd41409d3fba8df9d914112edb5ab4fdcae025bcf3571ade80349fc752e0af309559a91e55a382238b19f93

test:
  secret_key_base: 6ef3eeba44601025ff1a14a5caa0aef249b3bcf1ce132af8053446d7ebf5fa8ad70d5edd4b7633ca92783b20c740b6507d2085257d4ea7285945dc7753a56750

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
